Feature/project initialization
ShinhyoBelok/Bookstore pull request #1
Opened 2023-01-19 22:00 UTC by ShinhyoBelok

# Changes ♻️ 

I create the React part of the Bookstore website.

* Add book as a re-usable component.
* Add form to add a new book.
* Add main page books.
* Add categories page.

2023-01-19 23:48 UTC, Owusu-Desmond requested changes
Hi @ShinhyoBelok :wave: , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/KBVXhKkcvnYPZKiVTg/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 23:48 UTC, Owusu-Desmond commented on README.md
> +
- [ ] If you have no FAQ then I think it is better if you remove this section since it is optional :smile:

2023-01-19 23:48 UTC, Owusu-Desmond commented on README.md
> +## 👥 Authors <a name="authors"></a>
- [ ] Let's fix this typo, Please since you are the only contributor to this project you can singularize the `Authors` section to `Author` :smile:

2023-01-19 23:48 UTC, Owusu-Desmond commented on README.md
> +
- [ ] Please let's fix this, the project dev dependencies need to be installed before someone can use the app so it is better if you consider bringing the `Install` section before the `Usage` section. :pray:

2023-01-19 23:48 UTC, Owusu-Desmond commented on README.md
> +
- [ ] If you have no command to be run for deployment then it is better you remove this `Deployment` section rather than including this broken link.

2023-01-20 14:13 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 14:40 UTC, merged